accounts/urls.py
from django.urls import path
from accounts.views import \
    SubmittableLoginView, SubmittablePasswordChangeView, SuccessMessagedLogoutView, SignUpView

app_name = 'accounts'
urlpatterns = [
    path('login/', SubmittableLoginView.as_view(), name='login'),
    path('passwordchange/', SubmittablePasswordChangeView.as_view(), name='password_change'),
    path('logout/', SuccessMessagedLogoutView.as_view(), name='logout'),
    path('signup/', SignUpView.as_view(), name='signup'),
]

core/urls.py
from django.urls import path
from .views import EventCreateView, EventUpdateView, EventDetailView, EventDeleteView, \
    SearchEventView, EventMyView, EventFilterView, post_comment
from .filters import EventFilter


app_name = 'core'
urlpatterns = [
    path('event/create', EventCreateView.as_view(), name='event_create'),
    path('event/update/<pk>', EventUpdateView.as_view(), name='event_update'),
    path('event/detail/<pk>', EventDetailView.as_view(), name='event_detail'),
    path('event/delete/<pk>', EventDeleteView.as_view(), name='event_delete'),
    path('event/search', SearchEventView.as_view(), name='event_search'),
    path('event/comment/<event_id>', post_comment, name='event_comments'),
    path('event/my', EventMyView.as_view(), name='event_user_section'),
    path('event/filter', EventFilterView.as_view(filterset_class=EventFilter, template_name='filter.html'),
         name='event_filter'),
]

event_advisor/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import IndexView, AboutUs
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('about_us/', AboutUs.as_view(), name='about_us'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('core/', include('core.urls', namespace='core')),
    url(r'^ratings/', include(('star_ratings.urls', 'ratings'), namespace='ratings')),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

event_advisor/views.py
from core.views import EventListView


class IndexView(EventListView):
    template_name = 'index.html'


class AboutUs(EventListView):
    template_name = 'about_us.html'

event_advisor/templates/about_us.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block dropdown %}
    <div class="dropdown-menu">
        <a class="dropdown-item" href="{% url 'index' %}">Home</a>
      {% if logged_in == True %}
        <a class="dropdown-item" href="{% url 'core:event_user_section' %}">My events!</a>
      {% else %}
        <a class="dropdown-item" href="{% url 'accounts:login' %}">Log in firstly!</a>
      {% endif %}
      {% if permission == 1 %}
        <a class="dropdown-item" href="{% url 'core:event_create' %}">Add an event!</a>
      {% endif %}
    </div>
{% endblock %}

{% block content %}
<head>
  <meta charset="utf-8">
  <style>
  * {
box-sizing:
border-box;
}
body {
margin: 0;
}
.container-width {
width:90%;
max-width:1150px;
margin:0 auto;
}
.bdg-sect {
padding-top:100px;
padding-bottom:100px;
font-family:Helvetica, serif;
background-color:#fafafa;
}
.bdg-title {
text-align:center;
font-size:2em;
margin-bottom:55px;
color:#555555;
}
.badges {
padding:20px;
display:flex;
justify-content:space-around;
align-items:flex-start;
flex-wrap:wrap;
}
.badge {
width:290px;
font-family:Helvetica, serif;
background-color:white;
margin-bottom:30px;
box-shadow:0 2px 2px 0 rgba(0, 0, 0, 0.2);
border-radius:3px;
font-weight:100;
overflow:hidden;
text-align:center;
}
.badge-header {
height:115px;
background-image:url("//grapesjs.com/img/bg-gr-v.png"), url("//grapesjs.com/img/work-desk.jpg");
background-position:left top, center center;
background-attachment:scroll, fixed;
overflow:hidden;
}
.badge-name {
font-size:1.4em;
margin-bottom:5px;
}
.badge-role {
color:#777;
font-size:1em;
margin-bottom:25px;
}
.badge-avatar {
width:100px;
height:100px;
border-radius:100%;
border:5px solid #fff;
box-shadow:0 1px 1px 0 rgba(0, 0, 0, 0.2);
margin-top:-75px;position:relative;
}
.badge-body {
margin:35px 10px;
}
.badge-foot {
color:#fff;
background-color:#a290a5;
padding-top:13px;
padding-bottom:13px;
display:flex;
justify-content:center;
}
.badge-link {
height:35px;
width:35px;
line-height:35px;
font-weight:700;
background-color:#fff;
color:#a290a5;
display:block;
border-radius:100%;
margin:0 10px;
}
#ik18t {
font-family:Lucida Sans Unicode, Lucida Grande, sans-serif;font-size:36px;
}
</style>
</head>
<body>
<section class="bdg-sect" id="inihf">
  <h1 class="bdg-title" id="ik18t">AMT Team<br/></h1>
  <div class="container-width" id="ibybj">
    <div class="badges" id="i9d8y">
      <div class="badge">
        <div class="badge-header" id="i8jnug"></div>
        <img src="/media/Amadi.png" class="badge-avatar" id="io06tn"/>
        <div class="badge-body"><div class="badge-name" id="iuua8k">Amadeusz Walas<br/></div>
          <div class="badge-role" id="ictnyc">Junior Python Developer<br/></div>
        </div>
        <div class="badge-foot">
          <span class="badge-link"><a href="https://github.com/Bambamdilla">Git</a></span>
          <span class="badge-link"><a href="https://www.linkedin.com/in/amadeusz-walas-993b97b7/">in</a></span></div>
      </div>
      <div class="badge"><div class="badge-header"></div>
        <img src="/media/Mateusz2.png" class="badge-avatar"/>
        <div class="badge-body" id="i7lw5g"><div class="badge-name" id="ioms4h">Mateusz Telega<br/></div>
          <div class="badge-role" id="ijo1w4">Software Tester, Junior Python Developer<br/></div>
        </div>
        <div class="badge-foot">
          <span class="badge-link"><a href="https://github.com/MateuszTelega/">Git</a></span>

        </div>
      </div>
      <div class="badge"><div class="badge-header"></div>
        <img src="/media/Tomek.jpg" class="badge-avatar" id="idg0pj"/>
        <div class="badge-body"><div class="badge-name" id="igidle">Tomasz Wasiewicz<br/></div>
          <div class="badge-role" id="iwu4lz">Junior Python Developer<br/></div>
        </div>
        <div class="badge-foot">
          <span class="badge-link"><a href="https://github.com/Greavity">Git</a></span>
          <span class="badge-link"><a href="https://www.linkedin.com/in/tomasz-wasiewicz-534070154/">in</a></span></div>
      </div>
    </div>
  </div>
</section>
</body>
{% endblock %}

event_advisor/templates/base.html
{% load bootstrap4 %}
{% load static %}

<html {% if LANGUAGE_CODE %}lang="{{ LANGUAGE_CODE }}"{% endif %}>

  <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <title>Event Advisor</title>
      {% block styles %}{% bootstrap_css %}{% endblock %}
      {% block scripts %}{% bootstrap_javascript jquery='full' %}{% endblock %}
  </head>

   <style>
  body {
  background-image: url("/media/trawnik.jpg");
  background-repeat: no-repeat;
  background-attachment: fixed;
  background-size: 100% 100%;
  }

  </style>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <div class="container fixed">
       <a class="navbar-brand" href="{% url 'index' %}">
          <img src="/media/logo.png" style="width:400px; height:40px" alt="Event Advisor"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup">
          <span class="navbar-toggler-icon"></span>
        </button>
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <div class="nav-item dropdown">
              <a class="nav-link active dropdown-toggle" href="#" data-toggle="dropdown">
                <button class="btn btn-primary">Events</button>
              </a>
              {% block dropdown %}{% endblock %}
            </div>
            <form class="form-inline my-2 my-lg-0" method="GET" action="{% url 'core:event_search' %}" >
              <input class="form-control mr-sm-2" type="search" name="search">
              <button class="btn btn-primary" type="submit"> Search </button>

            </form>
          </div>
          <div class="navbar-nav">
          <div class="nav-item dropdown">
            <a class="nav-link active dropdown-toggle" data-toggle="dropdown">
              <button class="btn btn-primary">Filter</button>
            </a>
          <div class="dropdown-menu dropdown-menu-right">
          <form method="GET" action="{% url 'core:event_filter' %}">
            {{ filter.form }}
            <button type="submit" class="btn btn-primary">Search</button>
            <a class="btn btn-warning" href="{% url 'index' %}">Reset</a>
          </form>
          </div>
          </div>
          </div>

          <div class="navbar-nav ml-auto">
            {% if not user.is_authenticated %}
            <a class="nav-item nav-link active" href="{% url 'accounts:signup' %}">
              Registration
            </a>
            {% endif %}
            <div class="nav-item dropdown">
              {% if user.is_authenticated %}
                <a class="nav-link active dropdown-toggle" href="{% url 'accounts:logout' %}" data-toggle="dropdown">
                  <button class="btn btn-primary">
                  {% if user.name %}Hello, {{ user.name }}!
                  {% else %}Hello, {{ user.login_email }}!{% endif %}
                  </button>
                </a>
                <div class="dropdown-menu dropdown-menu-right">
                  <a class="dropdown-item text-right" href="{% url 'accounts:logout' %}">Logout</a>
                  <a class="dropdown-item text-right" href="{% url 'accounts:password_change' %}">Change password</a>
                </div>
              {% else %}
                <a class="nav-item nav-link active" href="{% url 'accounts:login' %}">
                  Sign in
                </a>
                <div class="dropdown-menu dropdown-menu-right">
                  <a class="dropdown-item text-right" href="#">Login</a>
                </div>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    </nav>
    <div class="container">
      <div class="jumbotron">
        {% block content %}{% endblock %}
      </div>
    </div>
  </body>

<footer class="container">
  <p>&copy; Amadeusz & Tomasz & Mateusz 2020</p>
</footer>
</html>

event_advisor/templates/form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block dropdown %}
    <div class="dropdown-menu">
        <a class="dropdown-item" href="{% url 'index' %}">Home</a>
      {% if logged_in == True %}
        <a class="dropdown-item" href="{% url 'core:event_user_section' %}">My events!</a>
      {% else %}
        <a class="dropdown-item" href="{% url 'accounts:login' %}">Log in firstly!</a>
      {% endif %}
      {% if permission == 1 %}
        <a class="dropdown-item" href="{% url 'core:event_create' %}">Add an event!</a>
      {% endif %}
    </div>
{% endblock %}


{% block content %}
    {% crispy form %}
{% endblock %}

event_advisor/templates/index.html
{% extends "base.html" %}
{% load event_extras %}


{% block dropdown %}
    <div class="dropdown-menu">
        <a class="dropdown-item" href="{% url 'index' %}">Home</a>
      {% if logged_in == True %}
        <a class="dropdown-item" href="{% url 'core:event_user_section' %}">My events!</a>
      {% else %}
        <a class="dropdown-item" href="{% url 'accounts:login' %}">Log in firstly!</a>
      {% endif %}
      {% if permission == 1 %}
        <a class="dropdown-item" href="{% url 'core:event_create' %}">Add an event!</a>
      {% endif %}
    </div>
{% endblock %}

{% block content %}
  <style type="text/css">
  .display-1 {
  font-family: 'Verdana' bold;
  font-size: 42px;
  color: white;
  }

  .display-2 {
  font-family: 'Lucida Sans Unicode';
  font-size: 24px;
  }

  .container {
  font-family: 'Lucida Sans Unicode';
  font-size: 14px;
  text-shadow: 1px 1px
  }

  .about_us {
  background-image: url("/media/cheer-3.jpg");
  background-repeat: no-repeat;
  font-family: 'Verdana', bold;
  font-size: 26px;
  position: relative;
  text-align: center;
  color: #00ff00;
  text-shadow: 2px 2px #ff0000
  }

  .my_events {
  font-family: 'Lucida Sans Unicode';
  font-size: 24px;
  font-weight: bold;
  text-shadow: 1px 1px #ff0000
  }
  </style>
  <div class="jumbotron">
    <div class="about_us">

      <h1 class="display-1">Let's meet there!...</h1>
      <p>Find an amazing event you'd like to join and have fun!</p>
      <p><a class="btn btn-primary btn-lg" href="{% url 'about_us' %}" role="button">About us &raquo;</a></p>

    </div>
  </div>


{% if my_events == True %}
  <h1 class="my_events">Here you have all your events...</h1>
  <br>
{% endif %}

  <div class="container">
    <div class="row">
      {% for event in page_obj %}
        <div class="col-md-4">
          <h1 class="display-2">{% event_title_format event %}</h1>
          <h6>{% event_date_format event %}</h6>
          <p>{% event_description_format event %}</p>
          <p><a class="btn btn-secondary" href="{% url 'core:event_detail' event.pk %}" role="button">View details &raquo;</a></p>
        </div>
      {% endfor %}
    </div>

    <hr>

  </div>

  <nav aria-label="Page navigation example">
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page=1">First</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
            Previous
          </a>
        </li>
      {% endif %}
      <li class="page-item active">
        <a class="page-link" href="#">
          Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
        </a>
      </li>
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">
            Next
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
            Last
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endblock %}

event_advisor/templates/search.html
{% extends "base.html" %}
{% load event_extras %}

{% block dropdown %}
    <div class="dropdown-menu">
        <a class="dropdown-item" href="{% url 'index' %}">Home</a>
      {% if logged_in == True %}
        <a class="dropdown-item" href="{% url 'core:event_user_section' %}">My events!</a>
      {% else %}
        <a class="dropdown-item" href="{% url 'accounts:login' %}">Log in firstly!</a>
      {% endif %}
      {% if permission == 1 %}
        <a class="dropdown-item" href="{% url 'core:event_create' %}">Add an event!</a>
      {% endif %}
    </div>
{% endblock %}

{% block content %}
    {% for event in all_search_results %}
        <h2>{% event_title_format event %}</h2>
        <h6>{% event_date_format event %}</h6>
        <p>{% event_description_format event %}</p>
        <p><a class="btn btn-secondary" href="{% url 'core:event_detail' event.pk %}" role="button">View details &raquo;</a></p>
    {% empty %}
        <h2>No results found</h2>
    {% endfor %}
{% endblock %}