accounts/urls.py
from django.urls import path
from accounts.views import \
    SubmittableLoginView, SubmittablePasswordChangeView, SuccessMessagedLogoutView, SignUpView

app_name = 'accounts'
urlpatterns = [
    path('login/', SubmittableLoginView.as_view(), name='login'),
    path('passwordchange/', SubmittablePasswordChangeView.as_view(), name='password_change'),
    path('logout/', SuccessMessagedLogoutView.as_view(), name='logout'),
    path('signup/', SignUpView.as_view(), name='signup'),
]

core/urls.py
from django.urls import path
from .views import EventCreateView, EventUpdateView, EventDetailView, EventDeleteView, \
    SearchEventView, EventMyView, EventFilterView, post_comment
from .filters import EventFilter


app_name = 'core'
urlpatterns = [
    path('event/create', EventCreateView.as_view(), name='event_create'),
    path('event/update/<pk>', EventUpdateView.as_view(), name='event_update'),
    path('event/detail/<pk>', EventDetailView.as_view(), name='event_detail'),
    path('event/delete/<pk>', EventDeleteView.as_view(), name='event_delete'),
    path('event/search', SearchEventView.as_view(), name='event_search'),
    path('event/comment/<event_id>', post_comment, name='event_comments'),
    path('event/my', EventMyView.as_view(), name='event_user_section'),
    path('event/filter', EventFilterView.as_view(filterset_class=EventFilter, template_name='filter.html'),
         name='event_filter'),
]

event_advisor/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import IndexView, AboutUs
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('about_us/', AboutUs.as_view(), name='about_us'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('core/', include('core.urls', namespace='core')),
    url(r'^ratings/', include(('star_ratings.urls', 'ratings'), namespace='ratings')),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from accounts.models import User


class EventType(models.Model):
    name = models.CharField(max_length=20, unique=True)

    def __str__(self):
        return self.name


class Event(models.Model):
    title = models.CharField(max_length=100)
    date_from = models.DateField()
    date_to = models.DateField()
    place = models.CharField(max_length=100)
    start_time = models.TimeField()
    end_time = models.TimeField(null=True, blank=True)
    picture = models.ImageField(upload_to="uploaded", null=True, blank=True)
    description = models.TextField(max_length=1000, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    event_type = models.ForeignKey(EventType, null=True, blank=True, on_delete=models.SET_NULL)
    users = models.ManyToManyField(User, related_name='users')
    owner = models.ForeignKey(User, related_name='owner', on_delete=models.CASCADE, null=True)

    def __str__(self):
        return f"Event {self.title} starts {self.date_from} in {self.place}. Created {self.created}"


class Comment(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    comment = models.TextField(max_length=500, null=False, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    opinion = models.IntegerField(null=True)

    def __str__(self):
        return f"{self.user} comment {self.event} at {self.created}"

core/forms.py
import re
from datetime import date
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Row, Column, Submit
from django import forms
from django.core.exceptions import ValidationError
from .models import Event, Comment


def capitalized_validator(value: str):
    if value[0].islower():
        raise ValidationError('Value must be capitalized!')


class FutureDateField(forms.DateField):
    def validate(self, value):
        super().validate(value)
        if value < date.today():
            raise ValidationError('Only future dates allowed here.')


class EventForm(forms.ModelForm):

    class Meta:
        model = Event
        exclude = ['users', 'owner']

    title = forms.CharField(validators=[capitalized_validator])
    date_from = FutureDateField(
        initial=date.today,
        widget=forms.DateInput(format='%d-%m-%Y'),
        input_formats=('%d-%m-%Y', )
    )
    date_to = FutureDateField(
        initial=date.today,
        widget=forms.DateInput(format='%d-%m-%Y'),
        input_formats=('%d-%m-%Y', )
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            'title',
            Row(Column('date_from'), Column('start_time'), Column('date_to'), Column('end_time')),
            'place',
            'picture',
            'description',
            'event_type',
            Submit('submit', 'Submit'),
        )

    def clean_description(self):
        initial = self.cleaned_data['description']
        sentences = re.sub(r'\s*\.\s*', '.', initial).split('.')
        cleaned = '. '.join(sentence.capitalize() for sentence in sentences)
        return cleaned


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comment']

core/views.py
from datetime import date

import requests
from django.db.models import Q
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from .models import Event, Comment
from .forms import EventForm, CommentForm
from .filters import EventFilter
from django_filters.views import FilterView


class OrganizerRequiredMixin(UserPassesTestMixin):
    def test_func(self):
        return self.request.user.is_organizer


class OwnerRequiredMixin(UserPassesTestMixin):
    def test_func(self):
        user_id = self.request.user.pk
        event = Event.objects.get(pk=self.request.path_info.split('/')[-1])
        event_owner_id = event.owner_id
        return event_owner_id == user_id


class EventListView(ListView):
    model = Event
    paginate_by = 3

    def get_queryset(self):
        return super().get_queryset().filter(date_to__gte=date.today()).order_by('date_from', 'start_time')

    def get_context_data(self, *args, object_list=None, **kwargs):
        context = super().get_context_data(*args, object_list=None, **kwargs)

        context['my_events'] = False

        permission = 0
        if not self.request.user.is_anonymous:
            permission = self.request.user.is_organizer
        context['permission'] = permission

        is_logged_in = False
        if self.request.user.is_authenticated:
            is_logged_in = True
        context['logged_in'] = is_logged_in

        context['filter'] = EventFilter(self.request.GET, queryset=self.get_queryset())

        return context


class EventMyView(LoginRequiredMixin, ListView):
    model = Event
    paginate_by = 3
    template_name = 'index.html'

    def get_queryset(self):
        user = self.request.user
        return super().get_queryset().filter(users=user).order_by('date_from', 'start_time')

    def get_context_data(self, *args, object_list=None, **kwargs):
        context = super().get_context_data(*args, object_list=None, **kwargs)

        context['my_events'] = True

        permission = 0
        if not self.request.user.is_anonymous:
            permission = self.request.user.is_organizer
        context['permission'] = permission

        is_logged_in = False
        if self.request.user.is_authenticated:
            is_logged_in = True
        context['logged_in'] = is_logged_in

        context['filter'] = EventFilter(self.request.GET, queryset=self.get_queryset())

        return context


class EventCreateView(LoginRequiredMixin, OrganizerRequiredMixin, CreateView):
    title = 'Add Event'
    template_name = 'form.html'
    model = Event
    form_class = EventForm
    success_url = reverse_lazy('index')

    def handle_no_permission(self):
        return redirect('index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        permission = 0
        if not self.request.user.is_anonymous:
            permission = self.request.user.is_organizer
        context['permission'] = permission

        is_logged_in = False
        if self.request.user.is_authenticated:
            is_logged_in = True
        context['logged_in'] = is_logged_in

        return context

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(EventCreateView, self).dispatch(*args, **kwargs)

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.owner = self.request.user
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())


class EventUpdateView(LoginRequiredMixin, OwnerRequiredMixin, UpdateView):
    template_name = 'form.html'
    model = Event
    form_class = EventForm
    success_url = reverse_lazy('index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        permission = 0
        if not self.request.user.is_anonymous:
            permission = self.request.user.is_organizer
        context['permission'] = permission

        is_logged_in = False
        if self.request.user.is_authenticated:
            is_logged_in = True
        context['logged_in'] = is_logged_in

        return context


class EventDeleteView(LoginRequiredMixin, OwnerRequiredMixin, DeleteView):
    template_name = 'event_confirm_delete.html'
    model = Event
    success_url = reverse_lazy('index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        permission = 0
        if not self.request.user.is_anonymous:
            permission = self.request.user.is_organizer
        context['permission'] = permission

        is_logged_in = False
        if self.request.user.is_authenticated:
            is_logged_in = True
        context['logged_in'] = is_logged_in

        return context


class EventDetailView(DetailView):
    template_name = 'event_detail.html'
    model = Event
    form_class = CommentForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        q = {'comments': list(Comment.objects.filter(event=context['event'].id))}
        context.update(q)
        context.update({'add_comment': CommentForm()})

        permission = 0
        if not self.request.user.is_anonymous:
            permission = self.request.user.is_organizer
        context['permission'] = permission

        is_owner = False
        if self.request.user.pk == context['event'].owner_id:
            is_owner = True
        context['owner'] = is_owner

        is_logged_in = False
        if self.request.user.is_authenticated:
            is_logged_in = True
        context['logged_in'] = is_logged_in

        user = self.request.user
        event = self.model.objects.get(pk=context['event'].id)

        is_subscribed = False
        if is_logged_in and user in event.users.all():
            is_subscribed = True
        context['subscribed'] = is_subscribed
        context['users_list'] = ', '.join([user.name for user in event.users.all()])

        return context

    def post(self, request, pk):
        event = self.model.objects.get(pk=pk)
        user_subscribing = self.request.user

        if user_subscribing not in event.users.all():
            event.users.add(user_subscribing)
        else:
            event.users.remove(user_subscribing)
        event.save()

        return HttpResponseRedirect(reverse('core:event_detail', args=(pk,)))


class SearchEventView(ListView):
    model = Event
    template_name = 'search.html'
    context_object_name = 'all_search_results'

    def get_queryset(self):
        result = super(SearchEventView, self).get_queryset()
        query = self.request.GET.get('search')
        if query:
            lookups = Q(title__contains=query) | Q(owner__name__icontains=query) | Q(description__icontains=query)\
                      | Q(place__icontains=query) | Q(event_type__name__icontains=query)
            postresult = Event.objects.filter(lookups)
            result = postresult
        else:
            result = None
        return result

    def get_context_data(self, *args, object_list=None, **kwargs):
        context = super().get_context_data(*args, object_list=None, **kwargs)

        permission = 0
        if not self.request.user.is_anonymous:
            permission = self.request.user.is_organizer
        context['permission'] = permission

        is_logged_in = False
        if self.request.user.is_authenticated:
            is_logged_in = True
        context['logged_in'] = is_logged_in

        return context


class EventFilterView(FilterView):
    model = Event

    def get_queryset(self):
        super().get_queryset()

    def get_context_data(self, *args, object_list=None, **kwargs):
        context = super().get_context_data(*args, object_list=None, **kwargs)

        permission = 0
        if not self.request.user.is_anonymous:
            permission = self.request.user.is_organizer
        context['permission'] = permission

        is_logged_in = False
        if self.request.user.is_authenticated:
            is_logged_in = True
        context['logged_in'] = is_logged_in

        context['filter'] = EventFilter(self.request.GET, queryset=self.get_queryset())

        return context


def post_comment(request, *args, **kwargs):
    try:
        r = requests.post('http://agnesgru.pythonanywhere.com',
                          data={'wpisz_opinie': request.POST.get('comment')}).json()
        opinion = r['result_int']
    except Exception:
        opinion = None

    comment = Comment(comment=request.POST.get('comment'),
                      user_id=request.user.id,
                      event_id=kwargs['event_id'],
                      opinion=opinion,
                      )

    if request.user.id:
        comment.save()
        return HttpResponseRedirect(request.META['HTTP_REFERER'])
    else:
        messages.error(request, "You need to be login")
        return HttpResponseRedirect(request.META['HTTP_REFERER'])

core/templates/event_confirm_delete.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block dropdown %}
    <div class="dropdown-menu">
        <a class="dropdown-item" href="{% url 'index' %}">Home</a>
      {% if logged_in == True %}
        <a class="dropdown-item" href="{% url 'core:event_user_section' %}">My events!</a>
      {% else %}
        <a class="dropdown-item" href="{% url 'accounts:login' %}">Log in firstly!</a>
      {% endif %}
      {% if permission == 1 %}
        <a class="dropdown-item" href="{% url 'core:event_create' %}">Add an event!</a>
      {% endif %}
    </div>
{% endblock %}

{% block content %}
  <form method="post">
      {% csrf_token %}
      <p>
          Are you sure you want to delete event "{{ object.title }}" from the database?
      </p>
      <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

core/templates/event_detail.html
{% extends "base.html" %}
{% load event_extras %}
{% load static %}

{% block dropdown %}
    <div class="dropdown-menu">
        <a class="dropdown-item" href="{% url 'index' %}">Home</a>
      {% if logged_in == True %}
        <a class="dropdown-item" href="{% url 'core:event_user_section' %}">My events!</a>
      {% else %}
        <a class="dropdown-item" href="{% url 'accounts:login' %}">Log in firstly!</a>
      {% endif %}
      {% if permission == 1 %}
        <a class="dropdown-item" href="{% url 'core:event_create' %}">Add an event!</a>
      {% endif %}
    </div>
{% endblock %}

{% block content %}
  {% if owner == True %}
    <p><span><a class="btn btn-warning" href="{% url 'core:event_update' event.pk %}" role="button">Edit &raquo;</a>
    <a class="btn btn-danger" href="{% url 'core:event_delete' event.pk %}" role="button">Delete &raquo;</a></span></p>
  {% endif %}
  {% if event.picture.url != None %}
    <img src="{{ event.picture.url }}" class="img-fluid" alt="no picture"
         style="margin:10px 50px;max-height:300;width:auto;">
  {% endif %}
    <div class="event-title borderhead" style="font-family:'Verdana';font-size:30px;text-shadow: 1px 1px #660033">
        <b>{{ event.title }}</b>
    </div>
    <style type="text/css">
  body {
  background-image: url("/media/trawnik.jpg");
  background-repeat: no-repeat;
  background-attachment: fixed;
  background-size: 100% 100%;
  }

  table {
  border-collapse: separate;
  border-spacing: 60px 0;
  padding: 10px;
  background: linear-gradient(to top, transparent, white),
  url("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcS7tbypZjojr4Vq7c_54u2rdFtGiUszLQFHSg&usqp=CAU");
  }

  p.desc {
  overflow-wrap: break-word;
  text-align: justify;
  line-height: 1.6;
  font-family: "Helvetica", Times, serif;
  }

  p.titles {
  text-transform: uppercase;
  font-family: 'Lucida Sans Unicode';
  font-size: 16px;
  letter-spacing: 1px;
  padding: 5px;
  text-shadow: 1px 1px #660033
  }

  .line {
    top: 0;
    bottom: 0;
    width: 2px;
    background: #99004d;
    z-index: 1;
    }

  .agnes {
      color: #777777;
      font-size: x-small;
  }
    </style>
  <table>
    <tr>
    <th>Start date: {{  event.date_from }}</th>
    <th>End date: {{ event.date_to }}</th>
    </tr>
    <tr>
      <td>Start time: {{ event.start_time|time:"H:i" }}</td>
      <td>End time: {{ event.end_time|time:"H:i" }}</td>
    </tr>
  </table>
  <div class="line">
      <p class="titles"><b>Location:</b><br></p></div>
      <p class="desc"> {{ event.place }}</p>
  <div class="line">
      <p class="titles"><b>Description:</b></p></div>
    <p class="desc">{{ event.description }}</p>
  <div class="line">
      <p class="titles"><b>Event type:</b><br></p></div>
    <p class="desc"> {{ event.event_type }} </p>

  {% if logged_in == 1 and subscribed == False %}
    <p><strong>You are still not subscribed for this event...</strong></p>
    <form action="{% url 'core:event_detail' event.pk %}" method="post">
      {% csrf_token %}
      <p>
        <button type='submit' class="btn btn-success">Subscribe &raquo; </button>
      </p>
    </form>
    <p>People attending the event: {{ users_list }} </p>
  {% endif %}
  {% if logged_in == 1 and subscribed == True %}
    <p><strong>You are already subscribed for this event! Great! Enjoy!</strong></p>
    <form action="{% url 'core:event_detail' event.pk %}" method="post">
      {% csrf_token %}
      <p>
        <button type='submit' class="btn btn-success">Unubscribe &raquo; </button>
      </p>
    </form>
    <p>People attending the event: {{ users_list }} </p>
  {% endif %}
  <br>
<link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
<script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>
{% load ratings %}
{% ratings object %}
  <div class="line">
    <p class="titles"><b>Comments section:</b></p></div>

  {% for result in comments|dictsortreversed:"created" %}
  <div class="container">
    <div class="row">
        <div class="col-8">
            <div class="card card-white post">
                <div class="post-heading">
                    <div class="float-left meta">
                        <div class="title h7">
                            <a href="#"><b>{{ result.user }}</b></a>
                        </div>
                        <h6 class="text-muted time">{{ result.created }}</h6>
                    </div>
                </div>
                <div class="post-description">
                    <p>{{ result.comment }}</p>
                    <p class="agnes">AGnesgru comment system platform decide that this comment is:
                        {% if result.opinion == 0 %}
                            Negative
                        {% elif result.opinion == 1 %}
                            Positive
                        {% else %}
                            No opinion
                        {% endif %}
                    </p>
                </div>
            </div>
        </div>
    </div>
  </div>
  {% endfor %}
<form action="{% url 'core:event_comments' event.pk %}" method="post">
  {% csrf_token %}
  <div class="form-group">
      {{ add_comment }}
  </div>
  <input type="submit" value="Submit &raquo;" class="btn btn-success">
</form>
</body>

{% endblock %}

core/templates/filter.html
{% extends "base.html" %}
{% load event_extras %}

{% block dropdown %}
    <div class="dropdown-menu">
        <a class="dropdown-item" href="{% url 'index' %}">Home</a>
      {% if logged_in == True %}
        <a class="dropdown-item" href="{% url 'core:event_user_section' %}">My events!</a>
      {% else %}
        <a class="dropdown-item" href="{% url 'accounts:login' %}">Log in firstly!</a>
      {% endif %}
      {% if permission == 1 %}
        <a class="dropdown-item" href="{% url 'core:event_create' %}">Add an event!</a>
      {% endif %}
    </div>
{% endblock %}

{% block content %}
    {% for event in filter.qs %}
        <h2>{% event_title_format event %}</h2>
        <h6>{% event_date_format event %}</h6>
        <p>{% event_description_format event %}</p>
        <p><a class="btn btn-secondary" href="{% url 'core:event_detail' event.pk %}" role="button">View details &raquo;</a></p>
    {% empty %}
        <h2>No results found</h2>
    {% endfor %}
{% endblock %}